import React from 'react'
import { Inter } from 'next/font/google'
import AdminNav from '@/components/admin/AdminNav'
import AdminSideBar from '@/components/admin/AdminSideBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AdminLayout = ({children}) => {
  return (
    <div>
      <AdminNav/>
      <AdminSideBar/>
      {children}
    </div>

        
       
    

  )
}

export default AdminLayout