import React from 'react'
import { Inter } from 'next/font/google'
import AdminNav from '@/components/admin/AdminNav'
import AdminSideBar from '@/components/admin/AdminSideBar'
import { getCurrentUser } from '@/actions/getCurrentUser'
import Nulldata from '@/components/Nulldata'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const AdminLayout = async ({children}) => {
  const currentUser=await getCurrentUser();

if(!currentUser  ||  currentUser.role !== 'ADMIN'){
    return <Nulldata title="Oops! access denide" />
}
  return (
    <div className='flex '>
    <div className=''>
      <AdminNav/>
      </div>
      <div>
      {children}
      </div>
    </div>

        
       
    

  )
}

export default AdminLayout