
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/Footer'
import CartProvider from '@/providers/CartProvider'
import { SessionProvider } from 'next-auth/react'
import NavHome from '@/components/NavHome'
import Catagories from '@/components/Catagories'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const dynamic = "force-dynamic";
export default async function RootLayout({ Component, children, session, pageProps }) {



  return (
    <html lang="en">
      <body className=' bg-white'>

        <Toaster toastOptions={{
          style: {
            background: "rgb(51 65 85)",
            color: "#fff"
          }
        }} />


        <CartProvider>

          <div>
          <NavHome/>
       
     
          
            <main >

              {children}

            </main>

        
          </div>

        </CartProvider>



      </body>
    </html>
  )


}
