import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import CartProvider from '@/providers/CartProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
 
 

  return (
    <html lang="en">
      <body>

     <Toaster toastOptions={{
          style:{
            background:"rgb(51 65 85)",
            color:"#fff"
          }
        }}/>
        <CartProvider>
        <div>
        <Nav/>
        <main>{children}</main>
        <Footer/>
        </div>
        </CartProvider>
        </body>
    </html>
  )

  
}
